name: Backend CI/CD

on:
  push:
    paths:
      - 'nomadai-for-study/**'
    branches: [ main ]
  pull_request:
    paths:
      - 'nomadai-for-study/**'
    branches: [ main ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        cd nomadai-for-study
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        cd nomadai-for-study
        echo "백엔드 테스트 실행 (추후 추가예정)"

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: nomadai-465512

    - name: Configure Docker for GCR
      run: gcloud auth configure-docker

    - name: Build and push Docker image
      run: |
        cd nomadai-for-study
        docker build -t gcr.io/nomadai-465512/nomadai-backend:${{ github.sha }} .
        docker push gcr.io/nomadai-465512/nomadai-backend:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy nomadai-backend \
          --image gcr.io/nomadai-465512/nomadai-backend:${{ github.sha }} \
          --platform managed \
          --region asia-northeast3 \
          --allow-unauthenticated
          --set-env-vars CLAUDE_API_KEY=${{ secrets.CLAUDE_API_KEY }}