name: Frontend CI/CD

on:
  push:
    paths:
      - 'nomadai-frontend-for-study/**'
    branches: [ main ]
  pull_request:
    paths:
      - 'nomadai-frontend-for-study/**'
    branches: [ main ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        cd nomadai-frontend-for-study
        npm install
    
    - name: Run tests
      run: |
        cd nomadai-frontend-for-study
        echo "프론트엔드 테스트 실행 (추후 추가예정)"
    
    - name: Build
      run: |
        cd nomadai-frontend-for-study
        npm run build

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: nomadai-465512

    - name: Create production build
      run: |
        cd nomadai-frontend-for-study
        npm run build

    - name: Deploy to Cloud Storage
      run: |
        cd nomadai-frontend-for-study
        gsutil -m rsync -r -d dist/ gs://nomadai-frontend-bucket/

    - name: Set up Cloud Storage bucket for web hosting
      run: |
        gsutil web set -m index.html -e index.html gs://nomadai-frontend-bucket
        gsutil iam ch allUsers:objectViewer gs://nomadai-frontend-bucket